# Generated by Django 3.2.4 on 2021-06-14 03:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhoUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'custom auth user',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('info', models.JSONField(blank=True, null=True)),
                ('uid', models.PositiveIntegerField(default=None, unique=True)),
                ('login', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'user info',
            },
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='who.whouser')),
                ('token', models.TextField()),
                ('token_refresh', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'oauth2 token',
            },
        ),
    ]
